version: '3.4'

services:
  dockerwebserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "3001:80"
      - "3000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  webservice1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3002:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  webservice2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3003:80"

